### ISSUE TITLE
Samsung galaxy Note 8 (SM-N950F)

### ISSUE THREAD

**Issue by Cisco30** [vusec/drammer#17]
application drammer restart the phone immediately
Android 8.0.0

**Comment by SuperSandro2000** [comment]
SM-G955F (Galaxy S8 International exynos) crashes after the start too. Can barely see a permission window about IMEI.

**Comment by vvdveen** [comment]
This seems to be a problem with our app on the S8. I will look into this as soon as possible.

**Comment by AlejandroHCruz** [comment]
Hi, any news on this? :)

**Comment by vvdveen** [comment]
Unfortunately not. I do not have access to a S8 yet.

**Comment by Sboeli** [comment]
works on nexus 5x but
on the Cat S30 get the install permision schreen but unable to install or run.
