### ISSUE TITLE
Add to F-Droid ?

### ISSUE THREAD

**Issue by breversa** [vusec/drammer#19]
Hi,

I'd like to make a request to add Drammer to F-Droid (www.f-droid.org).
Do the authors of Drammer support this inclusion (they don't need to do anything else ; the addition will be made by the F-Droid team) ?

**Comment by vvdveen** [comment]
This is on the backburner. F-Droid requires source code for the app, which we should clean up a bit before releasing.

**Comment by vvdveen** [comment]
F-Droid forces you to remove any Google libraries (we use some), and has some other requirements on how to build the app. We currently don’t have any time to fix this now, and we think that there is not much benefit in doing this in addition to open sourcing the native code. 

Closing this issue until further notice.

**Comment by vvdveen** [comment]
We open sourced the app code here: https://github.com/vusec/drammer-app/
