### ISSUE TITLE
Drammer Crashes

### ISSUE THREAD

**Issue by XIDNIOUS** [vusec/drammer#21]
Rooted using Towel Root.
Samsung Galaxy S5 Active (SM-G870A)
4.4.2 Kitkat (Locked bootloader)
SE Enforcing.
Instant app crash upon tapping.

**Comment by vvdveen** [comment]
Thanks for reporting! We hope to look into crashes like this eventually, but unfortunately not anytime soon. Your best bet is to compile and run the native binary directly.
