### ISSUE TITLE
Mem exhausted error when there is memory left.

### ISSUE THREAD

**Issue by bjorn3** [vusec/drammer#3]
Android 4.1.2
About 100 MB of 400MB left.

![screenshot_2016-10-25-10-33-32](https://cloud.githubusercontent.com/assets/17426603/19678872/e059cf6a-9a9f-11e6-8b3b-2c6a97c81f7d.png)

Mayby my android is too old.

**Comment by stephand** [comment]
Same here on nightly Android 6.0.1 (CM13) nightly build on a Galaxy S4 mini DSDS.

**Comment by vvdveen** [comment]
I've updated the binary used by the app, as well as the source to no longer exit when this happens. Hope it works...
