### ISSUE TITLE
Acer Liquid Z330 - assertion failed

### ISSUE THREAD

**Issue by screwer** [vusec/drammer#5]
Drammer console output:

[MAIN] ION init
Detected chipset: Qualcomm
[MAIN] No or weird row size provided, trying auto detect
[RS] Trying getprop
[RS] ro.product.model: T01
[RS] ro.product.name: T01_ww
[RS] ro.product.board: MSM8909
[RS] ro.board.platform: msm8909
[RS] Allocating 256K ion chunk
[RS] Reading from page 0 and page x (x = 0..64)
179 178 178 178 178 178 178 178 266 178 178 179 178 178 184 180 266 178 178 179 179 178 179 178 266 178 178 179 178 178 179 178 267 178 178 184 180 178 179 178 266 178 178 179 178 178 179 178 266 179 178 179 178 178 179 178 270 180 178 178 179 178 178 178
[RS] Median: 178
[RS] MAD: 0
[RS] IQR: 1
[RS] Corrected IQR: 6
[RS] Sequences: 8 1 7 1 7 1 7 1 7 1 7 1 7 1
[RS] Detected row size: 32768
[MAIN] Row size: 32768
[MAIN] Exhaust ION chunks for templating
[EXHAUST] - order 10 (4096 KB) - got   0 chunks
[EXHAUST] - order  9 (2048 KB) - got   0 chunks
[EXHAUST] - order  8 (1024 KB) - got  19 chunks
[EXHAUST] - order  7 ( 512 KB) - got  77 chunks
[EXHAUST] - order  6 ( 256 KB) - got 222 chunks
[EXHAUST] - order  5 ( 128 KB) - got 469 chunks
[EXHAUST] allocated 175744 KB (171 MB)
[MAIN] Initializing patterns
[MAIN] Start templating
[TMPL] - Bytes allocated: 179961856 (171 MB)
[TMPL] - Time: 1477950871
[TMPL] - Start templating
helper.h:63: uintptr_t get_phys_addr(uintptr_t): assertion "value & (1ULL << 63)" failed
Aborted

**Comment by vvdveen** [comment]
This issue should have been fixed already (the assertion is removed from the code). Can you try the latest master branch?
